version: "3"
services: 
    app:
        container_name: app_node
        build: 
            context: "../"
    zookeeper:
        container_name: zookeeper
        image: "bitnami/zookeeper:latest"
        ports: 
            - "2181:2181"
        environment: 
            - "ALLOW_ANONYMOUS_LOGIN=yes"
    kafka:
        container_name: kafka
        image: "bitnami/kafka:latest"
        ports: 
            - "9092:9092"
        environment: 
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
    
    db:
        image: mysql
        volumes: 
            - "../.docker/mysql/config:/etc/mysql/conf.d/config-file.cnf"
            - "../.docker/mysql/data:/var/lib/mysql:rw"
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            
    adminer:
        container_name: Adminer
        image: adminer
        restart: always
        ports:
        - 8080:8080